### ISSUE TITLE
[BUG] changeOwner not working on Goerli

### ISSUE THREAD

**Issue by tnkhanh** [uport-project/ethr-did#93]
Hi, I'm trying Ethr-did on the `goerli` testnet.
I tried sending a few `changeOwner` requests today in `goerli` with NodeJS.
I checked the transactions at
https://goerli.etherscan.io/address/0xdca7ef03e98e0dc2b855be647c39abe984fcf21b
One of the `changeOwner` transactions is successful but 3 other fail. What is the reason here?
I would like to check myself the reason it fails, too, if possible.
Thanks!

**Comment by mirceanis** [comment]
This is not a bug, it works exactly as expected.
Only the owner can make changes to an identity.

By default, an address is its own owner, but once you change it to a new owner, only the new owner can make further changes.

The first transaction, coming from the original works, but the next 3 transactions are also all coming from the original owner, so they should not work any more since the first transaction changed the owner successfully.

**Comment by tnkhanh** [comment]
Thanks. That makes sense!
